addpath(genpath('../FID-A-master'));
path = fullfile('braino','braino_01.SDAT');
data = io_loadspec_sdat(path,1);
us = Undersampler();

fids = data.fids;
Nx = 16;
Ny = 16;
Nt = size(fids,1);
fids = reshape(fids, [Nt, Nx, Ny]);
fids = permute(fids, [2 3 1]); 
ref = fftshift(fftn(fids));
[Ku, U] = us.undersample(fids,3,'poisson_disc');
disp(numel(U) / nnz(U));
specs = fftshift(fftn(Ku));
y0 = [0, 1 * max(abs(specs),[],'all')];
vis = Visualizer();
curr = fullfile(pwd,'brain_test.png');
% vis.visualize(flip(data.ppm),specs,'reverse',y0,[],curr,true);
error = norm(ref(:) - specs(:)) / norm(ref(:));
disp(error);
dwtmode('per','nodisp');
dwtmode;
rc_params = struct();
rc_params.rho = [1];
rc_params.ptol = [1e-2];
rc_params.dtol = [1e-2];
rc_params.mu = [10];
rc_params.gu = [2];
rc_params.gl = [2];
rc_params.scheme = 'dwt1';
rc_params.accel = 2;
rc_params.lambda = [1e-4];
rc_params.verbose = true;
Krc = dwt1(Ku,U,rc_params);

specs = fftshift(fftn(Krc));
error = norm(ref(:) - specs(:)) / norm(ref(:));
disp(error);
